// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATrmwnbKQMFF0blfaYL7jQo28fvcxNAT8',
    appId: '1:5010735255:web:d5b08ec9c4137efdf129d2',
    messagingSenderId: '5010735255',
    projectId: 'provisiontec-2761f',
    authDomain: 'provisiontec-2761f.firebaseapp.com',
    storageBucket: 'provisiontec-2761f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnJb37RMMIp_j9qyFNdoXqi6_uPzVE6Lk',
    appId: '1:5010735255:android:146790ff04ba8edff129d2',
    messagingSenderId: '5010735255',
    projectId: 'provisiontec-2761f',
    storageBucket: 'provisiontec-2761f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxAD9zolKp71ICUjJYRwoGT8K6tGrh8gU',
    appId: '1:5010735255:ios:c8c918f63846e9e3f129d2',
    messagingSenderId: '5010735255',
    projectId: 'provisiontec-2761f',
    storageBucket: 'provisiontec-2761f.appspot.com',
    iosBundleId: 'com.Provision.shopTec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxAD9zolKp71ICUjJYRwoGT8K6tGrh8gU',
    appId: '1:5010735255:ios:55c0d6491a02ca3af129d2',
    messagingSenderId: '5010735255',
    projectId: 'provisiontec-2761f',
    storageBucket: 'provisiontec-2761f.appspot.com',
    iosBundleId: 'com.example.shopTec',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATrmwnbKQMFF0blfaYL7jQo28fvcxNAT8',
    appId: '1:5010735255:web:bb4a4a470eeb521ef129d2',
    messagingSenderId: '5010735255',
    projectId: 'provisiontec-2761f',
    authDomain: 'provisiontec-2761f.firebaseapp.com',
    storageBucket: 'provisiontec-2761f.appspot.com',
  );

}